---
output: "parmigiano_full_coding"
simulate: False
permute_anno: False
model: "parmigiano" 
burden_prior: False

burden_model: "/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/parmigiano/true/pergene_burden_coding_updated"
epochs: 300
n_samples: 50
test_prop: 0.2
cell: 'coding' # must be coding, OLIG2, LHX2, NEUN, or peripheralPU1nuclei
enformer_preds: False ### MAKE THIS TRUE FOR ALL CELL TYPES
enformer_path: '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gene_matrices_maf/ADSP_rare_variants_enformer_delta_scores_annotations_neuron.tsv.gz'
lof_preds: False


fst_path: "/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/FST/36K_filtered_final_nmf/"
genes: 'fst' # fst, skat, staar, random, chr20, advp, etc
ngenes: 50 # if randomly selecting
threshold: 0.001 # if using existing test for joint test

# fixed parameters
output_path: '/gpfs/commons/home/adas/parmigiano/outputs/'
phenotype: '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/phenotypes/36K_QC_filtered_final.csv'
gene_matrices: '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gene_matrices_maf/'
covariates: ['Sex','Age','apoe_e4','apoe_e2','PC1', 'PC2','PC3','PC4','PC5','PC6', 'PC7','PC8','PC9','PC10', 'Illumina_HiSeq_2000', 'Illumina_HiSeqX','Illumina_NovaSeq', 'Illumina', 'USUHS', 'USUHS/Miami','NYGC', 'MEDGENOME', 'Baylor', 'Broad', 'WashU', 'PRS_5'] 
covariate_interactions: True
ancestry: "ALL" # 'EUR', 'EAS', 'AFR', 'AMR', 'SAS' or "ALL"
maf_weights: "observed" # must be gnomad or observed
imputation: "fixed"
lr: 0.1
annotations: 'NMF_PREP' # can be "all", list of annotations, "none", or "NNMF" or "NMF_PREP"
wg_separate: True
alpha_gene: True
